[project]
name = "countdown-monitor"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12.0"
dependencies = [
    "aiopytesseract>=1.1.0",
    "mss>=10.1.0",
    "opencv-python>=4.13.0.92",
    "pip>=26.0.1",
]
